FROM node:14-alpine

WORKDIR /app

COPY ./package.json ./

#RUN npm install
#RUN npm install --no-optional
# To solve installing fsevents on Mac M1 which I think it is regarded as Linux (no need to install it), but it is not
RUN npm i -f


COPY . .

CMD [ "npm", "run", "start" ]